# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f628595f5fe73e81a14fee36c453198a16770f7635c5eccefeca28c86505d62f35ddf445a1ac43ea1d0baf47d081756e27bccb50e105b97d81a690a95f6c1a4

test:
  secret_key_base: 36707d0a235b6069a70dd8590ebd9bfd0bee34ca683acbbdc8055f347c9db079d5c02835641d919397cdff37f15ed6caa2471ba31f05b3212924818f02f6b8a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
